config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  } 
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    put 'users/password/new', to: 'users/passwords#new'
    get 'users/password', to: 'users/passwords#edit'
    put 'users/password', to: 'users/passwords#update'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest' #ゲストログイン用
  end 

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
  root to: "blogs#index"
  
  resources :users, only: [:index, :new, :create, :show] do
    resources :relationships
    collection do
      get "follower"
    end
  end

  resources :blogs do
    collection do
      get 'confirm' 
    end
   resources :comments, only: :create
    collection do 
     get "search"
    end
  end  

  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image, dependent: :destroy

  validates :message_text,  presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @rooms = Room.where(id: @room.id)
    @messages = @room.messages.includes(:user)
     #roomに紐つくmessagesを全て定義。user情報も追加。
  end
  
  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user) #投稿に失敗しても@messageの情報を保持したままにできる。
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:message_text, :image).merge(user_id: current_user.id, room_id: @room.id)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<%= render "shared/header"%>
<%= render "shared/side_bar_room_message" %>

<div class="main-content">

 <div class="room-title">
  <div class="room-name">
   <%= @room.name %>
  </div>
    <%= link_to "ルーム削除", room_path(@room.id), method: :delete, class:"room-delete-btn"%>
 </div>

  <div class="blog-content-show">
      <div class="room-message-contents">
       <div class="message-text">
        <% if @messages %>
         <% @messages.each do |message|%>
          <div class="upper-message">
             <div class="message-user"><%# 投稿したユーザー情報を出力する %>
               <div class="message-username-block">
                <%= message.user.nickname %>さん:
               </div>
               <div class="message-date-block">
                (<%= message.created_at %>)
               </div>
             </div>
              <div class="message-content"><%# 投稿したメッセージ内容を記述する %>
               <%= message.message_text %>
              </div>
               <%= image_tag messages.image.variant(resize:'400x400'), class: 'message-image' if message.image.attached?%>
          </div>
         <% end %>
        <% end %>
       </div>
       <%= form_with model: [@room, @message], method: :post, local: true do |f| %>
        <div class="form-messages-content">
         <div class="form-message-block">
          <%= f.text_field :message_text, placeholder: "メッセージを入力してください", class:"message-form"  %>
           <div class="message-file">
            <%= f.label :image, class:"form-image-label" do %>
             <i class="fas fa-camera"></i>
              <%= f.file_field :image, class:"message-hidden" %>
            <% end %>
           </div>
           </div>
             <%= f.submit "送信", class:"message-btn" %>
        </div>
       <% end %>
      </div>
  </div>
</div>