config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  } 
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    put 'users/password/new', to: 'users/passwords#new'
    get 'users/password', to: 'users/passwords#edit'
    put 'users/password', to: 'users/passwords#update'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest' #ゲストログイン用
  end 

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
  root to: "blogs#index"
  
  resources :users, only: [:index, :new, :create, :show] do
    resources :relationships
    collection do
      get "follower"
    end
  end

  resources :blogs do
    collection do
      get 'confirm' 
    end
   resources :comments, only: :create
    collection do 
     get "search"
    end
  end  

  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }

  has_many   :blog_tags
  has_many   :tags, through: :blog_tags, dependent: :destroy
  has_many   :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_rich_text :body    # Actiontext

  validates :title,    presence: true

  # Blogテーブルとの検索データのやり取り
  def self.search(search)
    if search != ''
      @tag = Tag.where('tag_name LIKE(?)', "%#{search}%")
      @blog = Blog.where('title LIKE(?)', "%#{search}%")
        blogtags = BlogTag.where(tag_id: @tag.ids)
        blogtag = blogtags.pluck(:blog_id)
        blog = Blog.where(id: blogtag)
        @blog += blog
        @blog.uniq   #uniqで重複したやつは消す
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit destroy update]
  before_action :move_to_index, only: %i[edit new]

  def index
    @blogs = Blog.includes(:user).published.order('created_at DESC')
  end

  def confirm
    @blogs = Blog.draft.order('created_at DESC')
  end

  def new
    @blog = Blog.new(user_id: current_user.id)
    @blogs = Blog.where(id: params[:id])     # サイドバーに対してblogのidを配列として送る
  end

  def create
    @blog = BlogTags.new(blogtags_params)
    if @blog.valid?
      @blog.save
      redirect_to user_path(current_user.id)
    else
      @blog = Blog.new(user_id: current_user.id)  #これだとエラ〜メッセージが出ないのでflashなどを使用して改善する。
      render :new
    end
  end

  def destroy
    if @blog.destroy
      redirect_to user_path(current_user.id)
    else
      render :show
    end
  end

  def edit
    @tag_list = @blog.tags.pluck(:tag_name).join(',')
  end

  def update
    @newblog = BlogTags.new(blogtags_params)
    if @newblog.valid?
      @newblog.save
      @blog.destroy
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def show
    @user = current_user
    @comment = Comment.new
    @comments = @blog.comments.includes(:user)
  end

  def search
    @blogs = Blog.published.order('created_at DESC').search(params[:keyword])
    @blogs = [] if @blogs.nil?        #@bligsが空なら配列なしで展開する。
  end

  # 下書き・公開用
  def toggle_status!
    published if draft?
  end

  private

  def blogs_params
    params.require(:blog).permit(:title, :body, :image, :status, :comment).merge(user_id: current_user.id)
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :status, :image, :comment, :tag_ids).merge(user_id: current_user.id)
  end

  def blogtags_params
    params.require(:blog).permit(:title, :body, :status, :image, :comment, :tag_ids, :tag_name).merge(user_id: current_user.id)
  end

  def set_blog
    @blog = Blog.find(params[:id])
    @blogs = Blog.where(id: params[:id])
  end

  def move_to_index
    redirecto_to root_path unless user_signed_in? || @blog.user.id == current_user.id
  end

  # tag編集時のメソッド 構築途中
  # def save_tags(tag_list)
  #   current_tags = tag_list
  #   new_tags = blogtags_params[:tag_ids]
  #   tag_list = current_tags.replace(new_tags)
  #   new_tag_arry = tag_list.split(',')
  #   @tags = []
  #   new_tag_arry.each do |tag_name|
  #     @tag = Tag.where(tag_name: tag_name).first_or_initialize
  #     @tag.save!
  #     @tags << @tag
  #   end
  # end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<%# ブログ編集ページ %>
<%= render "shared/header" %>
 <%= render "shared/side_bar_edit" %>

    <%# 記事投稿フォーム作成 %>
   <%= render "shared/error_messages", model:@blog %>
 <div class="main-content">
  <div class="blog-head">
   <%= form_with model:@blog, url:blog_path, method: :put, local: true do |f| %>
    <div class="title-box"> 
     <div class="blog-title2">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class:"title-area", id:"title", placeholder:"記事タイトル" %>
     </div>
     <%# 画像投稿フォーム %>
     <div class="img-upload">
       <div class="img-text">
        見出し画像
       </div>
      <%= f.file_field :image, id:"blog-image"%>
     </div>
    </div>
  </div>

  <div class="blog-contents2">
     <%# 記事内容投稿フォーム %>
     <div class="blog-contribute">
       <div class="contribute-title">
        <%= f.label :body, "投稿内容作成" %>
       </div>
         <div class="tag-block">
           <%= f.text_field :tag_ids, value:@tag_list, class:"tag-form", placeholder:"タグをつける。複数つけるには','で区切ってください。"%>
         </div>
          <div class="action-btn">
           <%=f.select :status, Blog.statuses.keys.map { |k| [t("enums.blog.status.#{k}"),k]} %>
          </div>
           <div class="action-btn2">
            <%= f.submit "投稿", class:"contribute-btn"%>
           </div>
     </div>
      <%= f.rich_text_area :body, class:"blog-form", id:"text", placeholder:"記事内容"%>
   <% end %>
  </div>
</div>

app/views/blogs/index.html.erb
<%#header挿入%>
<div class="wrapper">
  <%= render "shared/header" %>

  <%# サイドUIコンテンツ %>
  <%= render "shared/side_bar"%>
 
  <%#メイン画面でブログを展開する%>
 <div class ="main-content">
    <%= render "shared/main_blog" %>
 </div>
   <%#footer挿入%>
   
</div>

app/views/blogs/new.html.erb
<%# ブログ投稿記事作成ページ %>
<%= render "shared/header" %>
 <%= render "shared/side_bar_edit"%>

    <%# 記事投稿フォーム作成 %>
     <%= render "shared/error_messages", model:@blog %>
<div class="main-content">
  <div class="blog-head">
   <%= form_with model:@blog, url: blogs_path, local: true do |f| %>
   <div class="title-box"> 
    <div class="blog-title2">
     <%= f.label :title, "タイトル:", class:"blog-title-label" %>
     <%= f.text_field :title, class:"title-area", id:"title", placeholder:"記事タイトル" %>
    </div>
    <%# 画像投稿フォーム %>
     <div class="img-upload">
       <%= f.label :image, class:"blog-image-label" do %>
        <i class="far fa-images"></i>
         <%= f.file_field :image, class:"message-hidden" %>
       <% end %>
     </div>
   </div>
  </div>

  <%# アイコンの類（取り敢えず並べたい） %>
 <div class="blog-contents2">
     <%# 記事内容投稿フォーム %>
    <div class="blog-contribute">
      <div class="contribute-title">
        <%= f.label :body, "投稿内容作成" %>
      </div>
         <div class="tag-block">
           <%= f.text_field :tag_ids, value:@tag_list, class:"tag-form", placeholder:"タグ入力。複数つけるには','で区切ってください。" %>
         </div>
          <div class="action-btn">
            <%=f.select :status, Blog.statuses.keys.map { |k| [t("enums.blog.status.#{k}"),k]} %>
          </div>
           <div class="action-btn2">
             <%= f.submit "投稿", class:"contribute-btn"%>
           </div>
    </div>
        <%= f.rich_text_area :body, class:"blog-form", id:"body", placeholder:"記事内容を入力してください。" %>
  <% end %>
 </div>
</div>

app/views/blogs/search.html.erb
<%# 検索ページ %>
<%= render "shared/header"%>
 <div class="side-bar">
  <%= render "shared/side_bar"%>
 </div>

<div class="main-content">
 <div class="title">
  search result
 </div>
  <div class="blog-contents">
   <%= render partial:"/shared/blog", locals:{blog: @blogs} %>
  </div>
</div>

app/views/blogs/show.html.erb
<%# 詳細ブログ記事ページ %>

<%# <タイトルヘッド部分> %>
 <%# if @blog.image.present? %>
  <%# <div class="head-index" style="background-image: url(<%= @blog.image );"> %>
  <div class="head-index" >
     <div class="title-index">
       <%= @blog.title %>
      <% if @blog.status == "draft"%>
        <div class="draft2">
         非公開
        </div>
      <%end%>
     </div>
  </div>

  <%= render "shared/side_bar2"%>
   <%= render "shared/error_messages", model: @comment%>

  <%# ページ内容 %>
<div class="main-content2">
  <div class="blog-contents-show">
      <%= @blog.body %>
   <% if user_signed_in? && @blog.user.id == current_user.id %>
    <%= render "shared/comment" %>
   <% elsif user_signed_in? %>
    <div class="blog-comment">
     コメント投稿 
    </div>
    <div class="comment-form">
     <%= form_with(model: [@blog, @comment], local: true) do |f| %>
      <%= f.text_area :text, placeholder: "コメントする", rows: "3" ,class:"comment-input"%>
       <%= f.submit "投稿する", class:"comment-btn" %>
     <% end %>
    </div>
      <%= render "shared/comment" %>
   <% else %>
      <%= render "shared/comment" %>
   <%end%>
  </div>
</div>

app/views/blogs/update.html.erb
<%# 詳細ブログ記事ページ %>

<%# <タイトルヘッド部分> %>
<% if @blog.image.present? %>
  <div class="head-index" style="background-image: url(<%= @blog.image %>);">
     <h1 class="title-index">
      <%= @blog.title %>
      </h1>
  </div>
  <% else %>
    <div class="head-index" >
     <h1 class="title-index">
      <%= @blog.title %>
      </h1>
   </div>
  <% end %>

 <%= render "shared/side_bar2"%>
  <%= render "shared/error_messages", model: @comment%>

  <%# ページ内容 %>
<div class="main-content2">
   <div class="blog-contents2">
     <div class="blog-report">
      <%= @blog.body %>
     </div>
   </div>
</div>