config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  } 
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    put 'users/password/new', to: 'users/passwords#new'
    get 'users/password', to: 'users/passwords#edit'
    put 'users/password', to: 'users/passwords#update'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest' #ゲストログイン用
  end 

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
  root to: "blogs#index"
  
  resources :users, only: [:index, :new, :create, :show] do
    resources :relationships
    collection do
      get "follower"
    end
  end

  resources :blogs do
    collection do
      get 'confirm' 
    end
   resources :comments, only: :create
    collection do 
     get "search"
    end
  end  

  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"  

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def index
   @user = User.find(params[:user_id])
  end

  def follow
    current_user.follow(params[:id])
    # redirect_to root_path
    if blog_path
    redirect_back(fallback_location: blog_path)
    else
    redirect_back(fallback_location: user_relationships_path)
    end
  end
  
  def unfollow
    current_user.unfollow(params[:id])
   if blog_path
    redirect_back(fallback_location: blog_path)
   else
    redirect_back(fallback_location: user_relationships_path)
   end
  end
  
  private
  def relationship_params
    params.require(:relationship).permit(follower_id: @user.id, followed_id: current_user.id )
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/index.html.erb
  <%= render "shared/header" %>
   <%= render "shared/side_bar_profile"%>

 <div class="main-content">
  <div class="title">
   フォロー / フォロワー・リスト
  </div>
   <div class="follow-contents">
     <div class="follow-content">
      <div class="follow-index">
       フォローしているユーザー
      </div>
       <div class="follow-sort">
        <% @user.following_user.where.not(id: @user.id).each do |user| %>
         <div class="follow-list">
          <% if user.image.present? %>
           <%= image_tag user.image, class: "user-img-follow" if user.image.attached? %>
          <% else %>
           <%= image_tag "no-image.jpeg", class: "user-img-follow"%>
          <% end %>

          <div class="follow-name-btn">
           <div class="follow-user">
            <%= link_to "#{user.nickname}さん", user_path(user.id), method: :get, class:"follow-nickname" %>
           </div>
            <% if user_signed_in? %>
             <div class="follow-btn-block">
              <% if current_user.following?(user) %>
               <div class="follow-chat-btn">
                <%= link_to "チャット", new_room_path(@user.id), class:"unfollow-btn"%>
               </div>
                <div class="follow-cancel-desbtn">
                 <%= link_to 'フォロー解除', unfollow_path(user.id), method: :POST, class:"unfollow-btn" %>
                </div>
              <% end %>
             </div>
            <% end %>
          </div>
         </div>
        <% end %>
       </div>
     </div>
     <div class="follow-content">
      <div class="follow-index">
       フォローしてくれているユーザー
      </div>
       <div class="follow-sort">
        <% @user.follower_user.where.not(id: @user.id).each do |user| %>
         <div class="follow-list">
           <% if user.image.present? %>
             <%= image_tag user.image, class: "user-img-follow" if user.image.attached? %>
           <% else %>
             <%= image_tag "no-image.jpeg", class: "user-img-follow"%>
           <% end %>
           <div class="follow-name-btn">
            <div class="follow-user">
             <%= link_to "#{user.nickname}さん", user_path(user.id), method: :get, class:"follow-nickname" %>
            </div>
            <% if user_signed_in? %>
             <div class="follow-btn-block">
              <% if current_user.following?(user) %>
               <%= link_to 'フォロー解除', unfollow_path(user.id), method: :POST, class:"unfollow-btn" %>
              <% else %>
               <% unless current_user.id == user.id%>
                <%= link_to 'フォローする', follow_path(user.id), method: :POST, class:"follow-btn" %>
               <% end %>
              <% end %>
             </div>
            <% end %>
           </div>
         </div>
        <% end %>
       </div>
      </div>
   </div>
 </div>