config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  } 
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    put 'users/password/new', to: 'users/passwords#new'
    get 'users/password', to: 'users/passwords#edit'
    put 'users/password', to: 'users/passwords#update'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest' #ゲストログイン用
  end 

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
  root to: "blogs#index"
  
  resources :users, only: [:index, :new, :create, :show] do
    resources :relationships
    collection do
      get "follower"
    end
  end

  resources :blogs do
    collection do
      get 'confirm' 
    end
   resources :comments, only: :create
    collection do 
     get "search"
    end
  end  

  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }

  has_many   :blog_tags
  has_many   :tags, through: :blog_tags, dependent: :destroy
  has_many   :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_rich_text :body    # Actiontext

  validates :title,    presence: true

  # Blogテーブルとの検索データのやり取り
  def self.search(search)
    if search != ''
      @tag = Tag.where('tag_name LIKE(?)', "%#{search}%")
      @blog = Blog.where('title LIKE(?)', "%#{search}%")
        blogtags = BlogTag.where(tag_id: @tag.ids)
        blogtag = blogtags.pluck(:blog_id)
        blog = Blog.where(id: blogtag)
        @blog += blog
        @blog.uniq   #uniqで重複したやつは消す
    end
  end
end

app/models/blog_tag.rb
class BlogTag < ApplicationRecord
  belongs_to :blog
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :blog, dependent: :destroy

  validates :text, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image, dependent: :destroy

  validates :message_text,  presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"  

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :users, through: :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one_attached :image, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :blog_tags
  has_many :blogs, through: :blog_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
  has_many :comments
  has_many :messages
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_one_attached :image
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  attr_accessor :current_password # user_editpasswordなしで更新に必要

  validates :nickname,       presence: true, length: { maximum: 10 }
  validates :full_name,      presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
  validates :full_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email,          presence: true, format: { with: /@+/ }

  validate :password_complexity
  
  def password_complexity
    return if password.blank? || password =~ /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z{6,}$/
    errors.add :password, 'は半角英数字で6文字以上で入力してください。'
  end

  #ゲストログイン用 find_byでゲスト検索。なければcreteする。
  def self.guest
    User.find_or_create_by(nickname: "ゲスト") do |user|
      user.nickname = "ゲスト"
    end
  end

  # ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit destroy update]
  before_action :move_to_index, only: %i[edit new]

  def index
    @blogs = Blog.includes(:user).published.order('created_at DESC')
  end

  def confirm
    @blogs = Blog.draft.order('created_at DESC')
  end

  def new
    @blog = Blog.new(user_id: current_user.id)
    @blogs = Blog.where(id: params[:id])     # サイドバーに対してblogのidを配列として送る
  end

  def create
    @blog = BlogTags.new(blogtags_params)
    if @blog.valid?
      @blog.save
      redirect_to user_path(current_user.id)
    else
      @blog = Blog.new(user_id: current_user.id)  #これだとエラ〜メッセージが出ないのでflashなどを使用して改善する。
      render :new
    end
  end

  def destroy
    if @blog.destroy
      redirect_to user_path(current_user.id)
    else
      render :show
    end
  end

  def edit
    @tag_list = @blog.tags.pluck(:tag_name).join(',')
  end

  def update
    @newblog = BlogTags.new(blogtags_params)
    if @newblog.valid?
      @newblog.save
      @blog.destroy
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def show
    @user = current_user
    @comment = Comment.new
    @comments = @blog.comments.includes(:user)
  end

  def search
    @blogs = Blog.published.order('created_at DESC').search(params[:keyword])
    @blogs = [] if @blogs.nil?        #@bligsが空なら配列なしで展開する。
  end

  # 下書き・公開用
  def toggle_status!
    published if draft?
  end

  private

  def blogs_params
    params.require(:blog).permit(:title, :body, :image, :status, :comment).merge(user_id: current_user.id)
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :status, :image, :comment, :tag_ids).merge(user_id: current_user.id)
  end

  def blogtags_params
    params.require(:blog).permit(:title, :body, :status, :image, :comment, :tag_ids, :tag_name).merge(user_id: current_user.id)
  end

  def set_blog
    @blog = Blog.find(params[:id])
    @blogs = Blog.where(id: params[:id])
  end

  def move_to_index
    redirecto_to root_path unless user_signed_in? || @blog.user.id == current_user.id
  end

  # tag編集時のメソッド 構築途中
  # def save_tags(tag_list)
  #   current_tags = tag_list
  #   new_tags = blogtags_params[:tag_ids]
  #   tag_list = current_tags.replace(new_tags)
  #   new_tag_arry = tag_list.split(',')
  #   @tags = []
  #   new_tag_arry.each do |tag_name|
  #     @tag = Tag.where(tag_name: tag_name).first_or_initialize
  #     @tag.save!
  #     @tags << @tag
  #   end
  # end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show destroy] 

  def index
    @rooms = Room.includes(:user)
  end

  def new
    @room = Room.new
    @rooms = Room.all
  end

  def create
    # @roomは既存のものがあればそのまま使用 first_or_initialize(保留)
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_messages_path(@room)
    else
      render :new
    end
  end

  def show
    @message = Message.find(params[:id])
  end
 
   def destroy
     if @room.destroy
       redirect_to new_room_path(current_user.id)
     else
      render :new
     end
   end
 
   private
   def room_params
     params.require(:room).permit(:name, user_ids:[])
   end

   def set_room
    @room = Room.find(params[:id])
   end

 end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>
</figure>
<%# 画像のキャプション部分 %>
  <%# <figcaption class="attachment__caption"> %>
    <%# <% if caption = blob.try(:caption) %> 
      <%# <%= caption %> 
    <%# <% else %> 
      <%# <span class="attachment__name"><%= blob.filename</span> %>
      <%# <span class="attachment__size"><%= number_to_human_size blob.byte_size </span> %>
    <%# <% end %> 
  <%# </figcaption> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <script src="https://kit.fontawesome.com/2f8d319b58.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-links-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-links-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_blog.html.erb
<%# ブログの検索結果を表示する %>
<% @blogs.each do |blog| %>
    <%= link_to blog_path(blog.id) do %>
      <div class="blog-block">
        <% if blog.image.present? %>
         <%= image_tag blog.image, class: "blog-img" if blog.image.attached? %>
        <% else %>
         <%= image_tag "no-image.jpeg", class: "blog-img"%>
        <% end %>
         <div class="blog-info">
          <li class="list">
           <div class="blog-title">
            <%= blog.title %>
           </div>
             <% if blog.status == "draft" %>
              <div class="draft">
               未公開
              </div>
             <% end %>
              <div class="blog-user">
               投稿者:
                <%= blog.user.nickname %>
              </div>
               <div class="blog-time">
                投稿日:
                <%= blog.created_at %>
               </div>
                <div class="tag-list">
                 <% blog.tags.each do |tag|%>
                  #<%= link_to "#{tag.tag_name}"%>
                 <% end %>
                </div>
          </li>
         </div>
      </div>
    <% end %>
<% end %>

app/views/shared/_comment.html.erb
 <div class="blog-comment">
      コメント一覧 
    </div>
    <div class="comments">
      <% if @comments %>
       <% @comments.each do |comment| %>
         <%= link_to comment.user.nickname, "/users/#{comment.user_id}", class:"comment-user" %>:
         <%= comment.text %>
         <div class="created-date">
         <%= comment.created_at %>
         </div>
       <% end %>
      <% end %>
    </div>  

app/views/shared/_error_messages.html.erb
<%# model事にエラーが出せるように設定 %>

<% if model.errors.any? %>
<div class="errors">
  <div class="error_explanation">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-messages"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/shared/_follow.html.erb
<%# フォロー人数表示など %>
<% "id: #{@user.id}" %>
<%= "フォロー数: #{@user.follower.count}"  %>
<%= "フォロワー数: #{@user.followed.count}" %>

<% unless @user == current_user %>
  <% if current_user.following?(@user) %>
    <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
  <% else %>
    <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
  <% end %>
<% end %>

<h3>フォロー一覧</h3>
  <% @user.following_user.where.not(id: current_user.id).each do |user| %>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <%= link_to "show", user_path(user) %>
  <% end %>
<h3>フォロワー一覧</h3>
  <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <%= link_to "show", user_path(user) %>
  <% end %>

app/views/shared/_follow_link.html.erb
<div class="follow-block">
   <div class="block">
    <%= link_to "#{@blog.user.nickname}さんの投稿一覧へ", user_path(@blog.user.id), method: :get, class:"nickname-link" %>
   </div>
   <% if user_signed_in? %>
    <% if current_user.following?(@blog.user) %>
     <div class="block">
      <%= link_to "フォロー解除する", unfollow_path(@blog.user.id), method: :POST, class:"unfollow-btn" %>
      </div>
    <% else %>
     <div class="block">
      <%= link_to "フォローする", follow_path(@blog.user.id), method: :POST, class:"follow-btn" %>
     </div>
    <% end %>
   <% end %>
</div>

app/views/shared/_header.html.erb
<div class="header">
<div class="header-left">
  <div class="title-block">
   <span class="s">S</span>imple<span class="s">B</span>log
  </div>
      <%# 検索フォーム %>
 <div class="nav-content">
  <div class="search-block">
   <%= form_with url: search_blogs_path, local: true, method: :get, class: "search-form"  do |f| %>
      <%= f.text_field :keyword, placeholder:"検索内容を入力してください", class:"search-input" %>
      <%= f.submit '検索', class:"search-btn" %>
   <% end %>
  </div>
 </div>
</div>

 <div class="header-right">
  <div class="user-list">
    <%# ログインしてるとマイページ。していなければログイン画面へ %>
   <% if user_signed_in? %>
     <%=link_to current_user.nickname, user_path(current_user.id), method: :get, class:"nickname"%>
   <% else %>
     <%=link_to "NoUser", user_session_path, class:"nickname"%>
   <%end%>
  </div>
    <%# ユーザーアカウント機能 %>
  <div class="sign-in">
    <% if user_signed_in? %>
     <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"log-out" %>
    <% else %>
     <%= link_to "新規登録",new_user_registration_path, class:"new-user"%>
     <%= link_to "簡単ログイン", users_guest_sign_in_path, method: :post, class:"log-in" %>
     <%= link_to "ログイン",user_session_path, class:"log-in" %>
    <% end %>
  </div>
 </div>
</div>

app/views/shared/_main_blog.html.erb
 <div class="title">
  投稿記事一覧
 </div>
  <div class="blog-contents">
   <%#ブログが存在したらブログ展開%>
    <% if @blogs.size > 0 %> 
     <%= render "shared/blog"%>
    <% end %>
  </div>

app/views/shared/_side_bar2.html.erb
<%# 個人ページ対応サイドバーコンテンツ %>
<div class="side-bar">
 <div class="side-contents">
  <div class="info">
   メニュー
  </div>
  
  <% if user_signed_in? %>
   <div class="side-menu">
      <div class="block">
       <%= link_to "マイページ", user_path(current_user.id), method: :get, class:"my-menu"  %>
      </div>
    <div class="block">
       <%= link_to "記事を書く", new_blog_path, class:"new-blog" %>
    </div>
    <div class="block">
       <%= link_to "チャット", new_room_path(current_user.id), class:"my-menu" %>
    </div>
  <% else %>
     <div class="block">
      <%= link_to "新規登録",new_user_registration_path, class:"new-user"%>
     </div>
     <div class="block">
      <%= link_to "ログイン",user_session_path, class:"log-in" %>
     </div>
  <% end %>
    <div class="block">
         <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
    </div>
   <div class="nav-content">
    <%= render "shared/side_search" %>
   </div>
 </div>

  <%# 下段UI %>
  <%# <自分のブログだけを表示したいが未定&& @blogs.ids(user_id: current_user.id)> %>
    <% if user_signed_in? && current_user.id == @blog.user_id  %>
     <div class="edit-block">
      <%= link_to "編集する", edit_blog_path, class:"edit-btn"%>
      <%= link_to "削除する", blog_path, method: :delete, class:"delete-btn"%>
     </div>
    <% else %>
     <%= render "shared/follow_link"%>
    <% end %> 
 </div>
</div>

app/views/shared/_side_bar3.html.erb
<%# 記事作成ページ対応サイドバーコンテンツ %>
<div class="side-contents">
  <div class="info">
   メニュー
  </div>
  
   
 <div class="side-menu">
   <% if user_signed_in? %>
    <div class="block">
       <%= link_to "マイページ", user_path(current_user.id), method: :get, class:"my-menu"  %>
    </div>
    <div class="block">
     <%= link_to "記事を書く", new_blog_path, class:"new-blog" %>
    </div>
   <% else %>
    <div class="block">
     <%= link_to "新規登録",new_user_registration_path, class:"new-user"%>
     </div>
     <div class="block">
     <%= link_to "ログイン",user_session_path, class:"log-in" %>
    </div>
   <% end %>
    <div class="block">
      <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
   </div>
  
  <div class="nav-content">
    <%= render "shared/side_search" %>
  </div>
 </div>
</div>

app/views/shared/_side_bar_edit.html.erb
<%# 記事作成ページ対応サイドバーコンテンツ %>
<div class="side-bar">
 <div class="side-contents">
  <div class="info">
   メニュー
  </div>
  <div class="side-menu">
    <% if user_signed_in? %>
     <div class="block">
       <%= link_to "マイページ", user_path(current_user.id), method: :get, class:"my-menu"  %>
     </div>
     <div class="block">
      <%= link_to "記事を書く", new_blog_path, class:"new-blog" %>
     </div>
    <% else %>
     <div class="block">
      <%= link_to "新規登録",new_user_registration_path, class:"new-user"%>
      </div>
      <div class="block">
      <%= link_to "ログイン",user_session_path, class:"log-in" %>
     </div>
    <% end %>
     <div class="block">
      <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
     </div>
  
   <div class="nav-content">
     <%= render "shared/side_search" %>
   </div>
  </div>
 </div>
</div>

app/views/shared/_side_bar_room.html.erb
<%# 記事作成ページ対応サイドバーコンテンツ %>
<div class="side-bar">
 <div class="side-contents">
  <div class="info">
   メニュー
  </div>
  <div class="side-menu">
    <% if user_signed_in? %>
     <div class="block">
       <%= link_to "マイページ", user_path(current_user.id), method: :get, class:"my-menu"  %>
     </div>
      <div class="block">
       <%= link_to "記事を書く", new_blog_path, class:"new-blog" %>
      </div>
       <div class="block">
        <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
       </div>
        <div class="info2">
        チャットルーム一覧
        </div>
         <% @rooms.each do  |room| %>
          <div class="block">
           <%= link_to room_messages_path(room.id) do %>
            <div class="my-menu">
             <%= room.name %>
            </div>
           <% end %>
          </div>
         <% end %>
    <% else %>
     <div class="block">
       <%= link_to "新規登録",new_user_registration_path, class:"new-user"%>
     </div>
      <div class="block">
       <%= link_to "ログイン",user_session_path, class:"log-in" %>
      </div>
       <div class="block">
        <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
       </div>
    <% end %>

  
   <%# <div class="nav-content"> %>
     <%#= render "shared/side_search" %>
   <%# </div> %>
  </div>
 </div>
</div>

app/views/shared/_side_bar_room_message.html.erb
<%# 記事作成ページ対応サイドバーコンテンツ %>
<div class="side-bar">
 <div class="side-contents">
  <div class="info">
   メニュー
  </div>
  <div class="side-menu">
    <% if user_signed_in? %>
     <div class="block">
       <%= link_to "マイページ", user_path(current_user.id), method: :get, class:"my-menu"  %>
     </div>
      <div class="block">
       <%= link_to "記事を書く", new_blog_path, class:"new-blog" %>
      </div>
       <div class="block">
        <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
       </div>
        <div class="info">
         ルーム参加者
        </div>
         <% @room.users.each do |user| %>
          <div class="member-block">
           <%= user.nickname %>さん
          </div>
         <%end%>
    <% else %>
     <div class="block">
       <%= link_to "新規登録",new_user_registration_path, class:"new-user"%>
     </div>
      <div class="block">
       <%= link_to "ログイン",user_session_path, class:"log-in" %>
      </div>
       <div class="block">
        <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
       </div>
    <% end %>
  </div>
 </div>
</div>

app/views/shared/_side_bar_user.html.erb
<%# サイドバーコンテンツ %>
<div class="side-bar">
 <div class="side-contents">
  <div class="info">
   メニュー
  </div>
   <% if user_signed_in? %>
      <div class="block">
       <%= link_to "マイページ", user_path(current_user.id), method: :get, class:"my-menu"  %>
      </div>
       <div class="block">
        <%= link_to "プロフィール",  users_path(current_user.id), method: :get, class:"my-menu"  %>
       </div>
        <div class="block">
         <%= link_to "記事を書く", new_blog_path, class:"new-blog" %>
        </div>
        <div class="block">
         <%= link_to "チャット", new_room_path(current_user.id), class:"my-menu" %>
        </div>
   <% else %>
    <div class="block">
     <%= link_to "新規登録",new_user_registration_path, class:"new-user"%>
    </div>
     <div class="block">
      <%= link_to "ログイン",user_session_path, class:"log-in" %>
     </div>
   <% end %>
    <div class="block">
     <%= link_to "一覧へ戻る", root_path, class:"root-index"%>
   </div>
    <div class="nav-content">
     <%= render "shared/side_search" %>
    </div>
  <%# 下段UI %>
  <div class="info2">
   過去投稿記事
  </div>
  <%# <自分のブログだけを表示したいが未定&& @blogs.ids(user_id: current_user.id)> %>
  <% if user_signed_in?  %>
   <% @blogs.each do |blog|%>
    <%= link_to blog_path(blog.id) do %>
     <div class="block">
      <div class="blog-name">
       <%= blog.title%>
      </div>
     </div>
    <% end %>
   <% end %>
  <%end %>
 </div>
</div>

app/views/shared/_side_search.html.erb
   <div class="search-block2">
    <%= form_with(url: search_blogs_path, local: true, method: :get, class: "search-form2" ) do |f| %>
     <%= f.text_field :keyword, placeholder:"検索内容を入力", class:"search-input2" %>
     <%= f.submit '検索', class:"search-btn2" %>
    <% end %>
   </div>